version: "3.4"
services:
  gkeep-sync:
    image: himynameisjonas/gkeep-matlistan:main
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/data
